version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: whatskovi-db
    environment:
      POSTGRES_USER: whatskovi
      POSTGRES_PASSWORD: whatskovi123
      POSTGRES_DB: whatskovi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - whatskovi-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whatskovi-backend
    environment:
      DATABASE_URL: postgresql://whatskovi:whatskovi123@postgres:5432/whatskovi?schema=public
      JWT_SECRET: your-super-secret-jwt-key-change-this
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-this
      JWT_EXPIRES_IN: 8h
      JWT_REFRESH_EXPIRES_IN: 7d
      PORT: 3001
      NODE_ENV: production
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/sessions:/app/sessions
    networks:
      - whatskovi-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whatskovi-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
      NEXT_PUBLIC_SOCKET_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - whatskovi-network

volumes:
  postgres_data:

networks:
  whatskovi-network:
    driver: bridge
